### ISSUE TITLE
Error on_select - message should be array

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#2]
**Request**

{
    "context": {
      "domain": "{{domain}}",
      "location": {
            "country": {
                "code": "IND"
            },
            "city": {
                "code": "std:080"
            }
        },
      "action": "select",
      "version": "{{version}}",
      "bap_id": "{{bap_id}}",
      "bap_uri": "{{bap_uri}}",
      "bpp_id": "{{bpp_id}}",
      "bpp_uri": "{{bpp_uri}}",
      "message_id": "5eab5b66-f2d7-4e7a-90fa-446fb49f754f",
      "transaction_id": "8100d125-76a7-4588-88be-81b97657cd57",
      "timestamp": "2023-11-06T09:44:47.217Z"
    },
    "message": {
        "order": {
            "provider": {
                "id": "Vendure_Default_Shop_Token"
            },
            "items": [
                {
                    "id": "89",
                    "quantity": {
                        "selected": {
                            "count": 1
                        }
                    }
                }
            ],
            "fulfillment": {
                "id": "f1"
            }
        }
    }
}

**Error**

[server] Error: {"message":{"ack":{"status":"NACK"}},"error":{"code":400,"message":"OpenApiValidator Error","data":{"name":"Bad Request","status":400,"path":"/on_select","errors":[{"path":".body.message.order.items","message":"should be array","errorCode":"type.openapi.validation"}]},"type":"DOMAIN-ERROR"}}
[server]     at GenericHandlerService._send_response_to_beckn (\projects\bpp-admin-app\src\plugins\beckn-vendure-plugin\src\generic-handler.service.ts:49:19)

**Comment by vbabuEM** [comment]
Issue occurs only when there is one item in the order. Fixed jsonata to consider single item also as an array.

**Comment by vbabuEM** [comment]
https://github.com/beckn/vendure/commit/2ede98fe1187dc19df434b538a001296ac8f746f
