### ISSUE TITLE
Add fulfillment_state object in on_status

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#26]
Beckn specification has fulfillment_state object included in on_status.  However, I'm not sure about the purpose of having a state object under fulfillments and also fulfillment_state as a separate object.  I'm assuming Beckn is in the direction of migrating to a dedicated fulfillment_state object.

**Comment by vbabuEM** [comment]
@sreekanthmr , where is this fulfillment_state object you mention. Can you please paste the yaml with the fulfillment_state property.
