### ISSUE TITLE
Add quantity object to item in on_search

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#27]
Different products and services will have different unit of measurement.  So, we will have to pass that information to front-end.  Beckn specification has quantity.unitized.measure under item, which we thought of using for this.

"quantity": {
                  "unitized": {                    
                    "measure" : {
                      "count":"1",
                      "unit" : "Bags"
                    }
                  }
                }

Similarly under Vendure, Product Options under Product Variant provides this ability.

@vbabuEM your thoughts please?

**Comment by vbabuEM** [comment]
@sreekanthmr , Sure. Basically you can use the following as a thumb rules on new features.
1. Any feature specified in Beckn protocol will be a valid feature request.
2. If the support for it in Vendure is not currently there, there will be additional effort to implement, but still that does not invalidate the request.
3. The priority can be decided using the effort and ROI as inputs.

**Comment by vbabuEM** [comment]
On this particular issue. Sure I think I should be able to add it. I will update this ticket of any difficulties after discovery.
