### ISSUE TITLE
Add name attribute to fulfillment state

### ISSUE THREAD

**Issue by vbabuEM** [beckn/vendure#30]

**Comment by vbabuEM** [comment]
@sreekanthmr , the fulfillment state that we return here is the detail order state. Within Vendure too, I found only code like ArrangingPayment and not a string "Arranging Payment". Please let me know if you have found the string returned in any Vendure API. If any API returns, we can try to use the same source. Till then I will move this to backlog.

**Comment by sreekanthmr** [comment]
> @sreekanthmr , the fulfillment state that we return here is the detail order state. Within Vendure too, I found only code like ArrangingPayment and not a string "Arranging Payment". Please let me know if you have found the string returned in any Vendure API. If any API returns, we can try to use the same source. Till then I will move this to backlog.

I'll check and revert

**Comment by vbabuEM** [comment]
No further response from field on this. Closing it for now.
