### ISSUE TITLE
Search by category returns products from all the categories

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#32]
When we search by a single category, the response we get has all the products from all the categories.

**Comment by vbabuEM** [comment]
@sreekanthmr , can you please paste the request you are sending.

**Comment by vbabuEM** [comment]
@sreekanthmr , please note that with the default search strategy in Vendure, the category name should match the case of the facet value. Also the facet name should be "category" in Vendure. In general I suggest following: Use lowercase in Vendure for facet names and start the facet values in Upper case. This is not a restriction, as long as you match the request with the data. The only restriction is that the name of the category facet should be "category" in lower case within vendure

**Comment by vbabuEM** [comment]
In consultation with @sreekanthmr , it was found out that this behaviour is only when the requested category is not present in the catalog.
