### ISSUE TITLE
Payment value has a floating point format in on_status response

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#34]
In On_status call, the returned payment value has a floating point format, while it should usually not show beyond cents(paise).

**Comment by vbabuEM** [comment]
@sreekanthmr , can you please paste an example. Also if it is in payment, then the original value is coming in from the BAP and it should be string. If it is any of the prices calculated by Vendure, we need to fix it.

**Comment by sreekanthmr** [comment]
@vbabuEM I tried to replicate the issue but was not able to find it.  I'll check again and update you.

**Comment by sreekanthmr** [comment]
This issue could be reproduced.  So, closing this.
