### ISSUE TITLE
Add authentication to secure the endpoints

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#36]
Can we have some kind of authentication for calling the endpoints?

**Comment by vbabuEM** [comment]
I think the easiest one I can think of is to use something like https://github.com/awesometic/nestjs-ip-filter and have the BPP-Client be whitelisted. What do you think?

**Comment by sreekanthmr** [comment]
Since it will be only one referer that we will need to configure, that should be fine I think.  Does it also support domain name apart from ip?

**Comment by vbabuEM** [comment]
I think writing a regex to give a private address range seems the easiest one from a maintenance perspective. There are examples of those in the plugin site.

**Comment by vbabuEM** [comment]
For now this will be done at a Vendure installation level rather than plugin level. Closing it for now.
