### ISSUE TITLE
Add search by rating

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#37]
We have requirement for searching by rating.  Is it possible to implement search by rating?

**Comment by vbabuEM** [comment]
What is the recommended Search Intent from the spec team for this @sreekanthmr ?

**Comment by sreekanthmr** [comment]
intent.item.rating is already supported in the spec.  When we did spec JSON definition, I got a confirmation on this from Mayank

**Comment by vbabuEM** [comment]
@sreekanthmr , since the value field of rating is flexible, can you please paste the intent that you want supported.

**Comment by vbabuEM** [comment]
Ratings search is not currently supported by Vendure. We need to figure out how to extend the Vendure search Shop-api to support this.

**Comment by sreekanthmr** [comment]
It is more practical to implement sort by rating at the front end app instead of having search by rating.  So, marking this enhancement as closed.
