### ISSUE TITLE
Product image links have localhost:port

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#38]
All image links in the responses have localhost:port.  Can we replace this with a URL that we configure the Vendure installation?  If there is no way to get it from request headers, can we have url as part of plugin config?

**Comment by vbabuEM** [comment]
@sreekanthmr , did you try the apiOptions configuration in VendureConfig

**Comment by sreekanthmr** [comment]
Thanks for flagging that out.  I'll check that.

**Comment by vbabuEM** [comment]
Issue solved by Sreekanth by setting apiOptions.
