### ISSUE TITLE
Order Id is too long to display in the BAP front-end app

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#39]
Is there a way we can have a shorter order id?  Right now it is too long to display in the front-end app.

**Comment by vbabuEM** [comment]
The order_id is the session id on vendure. This is core to the design. The UI itself does not have to show all the characters. It can be concatenated, as long as the API call sends the whole string. One of the reasons we retained this was the additional security we get through not easily guessable id. Check if you can use a strategy on UI. If you are unable to do so, we will have to add additional translation logic.

**Comment by sreekanthmr** [comment]
While what you mentioned makes sense....
Initially, we were generating an order ID and displaying it on the screen but I thought instead of leaving it for every front-end app to implement that logic, it would be easier to do it on the BPP side.  I'm now confused about which one is ideal.

**Comment by vbabuEM** [comment]
Not an issue anymore due to BAP design.
