### ISSUE TITLE
Explore location aware search

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#48]
To enable customers easily find products available in their vicinity, there is need to explore the possibility of making the search location aware.  Using the customer's geo location, we should be able to define an area of search (say 20 or 50kms) and return the providers operating within that boundary.

**Comment by vbabuEM** [comment]
@sreekanthmr , do you know of any plugin that already does this task on Vendure?

**Comment by sreekanthmr** [comment]
It is more practical to implement location aware search at the BAP front end app.  So, closing this issue.
