### ISSUE TITLE
For Digital Products, the order status is getting reset to Arranging Payments from Payment Settled

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#63]
Digital products with 0 value, we are trying to apply the zero dollar payment method and set the order status to Payment Settled automatically.  Though the order status is changing, somehow the order transition from beckn-vendure-plugin is taking effect after that and resetting the order status back to arranging payment.

**Comment by vbabuEM** [comment]
This bug occurs when the following code sent by Sreekanth is executed.
`
import { OrderProcess, OrderService } from '@vendure/core';

import { digitalFulfillmentHandler } from './digital-fulfillment-handler';



let orderService: OrderService;

function generateGUID(): string {
    const timestamp = new Date().getTime();
    const randomNum = Math.floor(Math.random() * 1000000);
    return ${timestamp}-${randomNum};
}
/**
 * @description
 * This OrderProcess ensures that when an Order transitions from ArrangingPayment to
 * PaymentAuthorized or PaymentSettled, then any digital products are automatically
 * fulfilled.
 */
export const digitalOrderProcess: OrderProcess<string> = {
    async onTransitionEnd(fromState, toState, data) {
        //If the order total value is 0 and has a digital product, change the payment status to "Settled"
        if (
            toState === 'ArrangingPayment'
        ) {
            const digitalOrderLines = data.order.lines.filter(l => l.productVariant.customFields.isDigital);
            if (digitalOrderLines.length && data.order.totalWithTax === 0) {
                let payments = data.order.payments;
                console.log('Order transitioning from ArrangingPayment to PaymentSettled');
                console.log(data.order);
                for (const payment of payments){
                    await orderService.settlePayment(data.ctx, payment.id); 
                } 
            }
        }
        //If the order has digital products and payment status is "Settled", transition the order fulfillment to fulfilled.
        if (
            fromState === 'ArrangingPayment' &&
            (toState === 'PaymentAuthorized' || toState === 'PaymentSettled')
        ) {
            const digitalOrderLines = data.order.lines.filter(l => l.productVariant.customFields.isDigital);
            if (digitalOrderLines.length) {
                await orderService.createFulfillment(data.ctx, {
                    lines: digitalOrderLines.map(l => ({ orderLineId: l.id, quantity: l.quantity })),
                    handler: { code: digitalFulfillmentHandler.code, arguments: [] },
                });
            }
        }
    },
};
`

**Comment by vbabuEM** [comment]
This ArrangingPayment issue that you pasted the code above, I feel it is not going into the payments loop in line 31.
I changed the code to simply transition the order directly and it seems to be working as far as the order state goes.
`import { OrderProcess, OrderService } from '@vendure/core';

import { digitalFulfillmentHandler } from './digital-fulfillment-handler';

let orderService: OrderService;

function generateGUID(): string {
    const timestamp = new Date().getTime();
    const randomNum = Math.floor(Math.random() * 1000000);
    return ${timestamp}-${randomNum};
}
/**
 * @description
 * This OrderProcess ensures that when an Order transitions from ArrangingPayment to
 * PaymentAuthorized or PaymentSettled, then any digital products are automatically
 * fulfilled.
 */
export const digitalOrderProcess: OrderProcess<string> = {
    init(injector) {
        orderService = injector.get(OrderService);
    },
    async onTransitionEnd(fromState, toState, data) {
        //If the order total value is 0 and has a digital product, change the payment status to "Settled"
        if (toState === 'ArrangingPayment') {
            const digitalOrderLines = data.order.lines.filter(l => l.productVariant.customFields.isDigital);
            if (digitalOrderLines.length && data.order.totalWithTax === 0) {
                orderService.transitionToState(data.ctx, data.order.id, 'PaymentSettled');
            }
        }
        //If the order has digital products and payment status is "Settled", transition the order fulfillment to fulfilled.
        if (
            fromState === 'ArrangingPayment' &&
            (toState === 'PaymentAuthorized' || toState === 'PaymentSettled')
        ) {
            const digitalOrderLines = data.order.lines.filter(l => l.productVariant.customFields.isDigital);
            if (digitalOrderLines.length) {
                await orderService.createFulfillment(data.ctx, {
                    lines: digitalOrderLines.map(l => ({ orderLineId: l.id, quantity: l.quantity })),
                    handler: { code: digitalFulfillmentHandler.code, arguments: [] },
                });
            }
        }
    },
};`

**Comment by vbabuEM** [comment]
Since this code is not in the plugin and it has been troubleshooted, I will close this issue.
