### ISSUE TITLE
Not getting order status for orders other than digital products

### ISSUE THREAD

**Issue by sreekanthmr** [beckn/vendure#67]
Not getting order status for orders, that are not digital products.  Not getting fulfilments object in order status response.

**Comment by vbabuEM** [comment]
I am able to see the fulfillments after they are added. Please remember that in case of non-digital order, fulfillments will only come after it is manually created at the vendure admin console. @sreekanthmr

**Comment by sreekanthmr** [comment]
This issue can be closed.  This issue is not observed with orders, which are created recently.  So, this could be related to missing plugin when the order was created.
