### ISSUE TITLE
Add rating endpoint to Plugin

### ISSUE THREAD

**Issue by vbabuEM** [beckn/vendure#7]
Some discovery might be needed on this. Check if the review rating plugin that Vendure has can fulfill this. Else this has to be retargeted to future sprints

**Comment by vbabuEM** [comment]
This feature involves the installation of the reviews plugin which is present in the [Vendure source repo](https://github.com/vendure-ecommerce/vendure). Use the following steps to install it.
1. Copy reviews module from the path `packages/dev-server/test-plugins/reviews` from the Vendure source repo.
2. npm install -D '@vendure/ui-devkit'
3. npm run dev

**Comment by vbabuEM** [comment]
This feature has only added the rating part of the rating request. Typically the rating request should give a form where user can input comments. This is achieve by X-Input. This is not done in this Issue. In addition, note the following:
1. Vendure requires Customer and Summary and Body fields. These are kept as "Customer","Customer Review" and "Customer Review" respectively.
2. Only product review is added in this Issue.
3. The message in on_rating will be an empty object.

**Comment by vbabuEM** [comment]
In Vendure the review needs to be approved before it is counted in the overall rating. You can approve it either through the UI (the admin UI has to be extended) or through admin API approveReview call.

**Comment by sreekanthmr** [comment]
> This feature involves the installation of the reviews plugin which is present in the [Vendure source repo](https://github.com/vendure-ecommerce/vendure). Use the following steps to install it.
> 
> 1. Copy reviews module from the path `packages/dev-server/test-plugins/reviews` from the Vendure source repo.
> 2. npm install -D '@vendure/ui-devkit'
> 3. npm run dev

Which directory should I execute npm run dev?
