### ISSUE TITLE
To add French Catalogs to City Of Lights and OSM

### ISSUE THREAD

**Issue by viraj89** [beckn/vendure#76]
### Description
The goal of this ticket is to add French catalogs to the City of Lights and OSM apps, similar to the current catalogs in Venky's Hum Bhi Online (HBO). These catalogs need to be migrated to Vendure dev environment. 

The catalogs are present here: 
1. https://retail-bpp-infra1.becknprotocol.io 
2. https://retail-bpp-infra2.becknprotocol.io 

### Goals
- [ ] Add French catalogs to the City of Lights and OSM apps.

### Expected Outcome
Successful addition of French catalogs to the City of Lights and OSM apps.

### Acceptance Criteria
- [ ] French catalogs are successfully added to the City of Lights and OSM apps.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn 

### Domain
Tourism, EComm

### Tech Skills Needed
- Catalog Management
- Vendure BPP

### Complexity
Medium

### Category
Catalog Management

### Sub Category
Migration

**Comment by vbabuEM** [comment]
Have added the catalogs with the same ids as that in Venky's BPP so the link with OSM is maintained.
